- name: Kamailio+rtpegine
  remote_user: root
  hosts: all
  gather_facts: true
  become: yes
  roles:
    - { role: os.common, tags: common }
    - { role: rtpengine.conf, tags: rtpengine }
    - { role: kamailio.conf, tags: kamailio }
    - { role: keepalived.conf, tags: keepalived }
